version: '3.7'

networks:
  nginx-mysql-php:

services:
#  nginx:
##    build:
##      context: .
##      dockerfile: /php/Dockerfile-nginx
#    image: nginx:latest
#    container_name: nginx-container
#    ports:
#      - "8000:80"
#    volumes:
#      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./:/var/www/project
#      - ./logs/nginx:/var/log/nginx
#    depends_on:
#      - mysql
#    links:
#      - php
#    networks:
#      - nginx-mysql-php

  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"
#    networks:
#      - nginx-mysql-php

#  php:
#    build:
#      context: .
#      dockerfile: ./php/Dockerfile-php
#      args:
#        app_env: ${APP_ENV}
#    container_name: php80-container
#    restart: always
#    ports:
#      - '9000:9000'
#    volumes:
#      - ./:/var/www/project
#    networks:
#      - nginx-mysql-php