version: '3.7'

networks:
  internal:
    driver: bridge

services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./:/srv/www/api
#      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php
#    networks:
#      - internal
#    links:
#      - php

  db:
    image: 'mysql:8.0'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
#    command: "mysqld --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
#    volumes:
#      - ./config/sql/init.sql:/data/application/init.sql
    networks:
      - internal

  php:
    container_name: php
    build:
      context: ./config/php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www/api
      - ./config/php/www.conf:/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    links:
      - db
    networks:
      - internal

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${IP}:8000:80
    links:
      - db:db
    networks:
      - internal
